# Generated by Django 4.0 on 2021-12-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuzzyurl', '0002_alter_shortner_options_remove_shortner_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortner',
            name='short_url',
            field=models.CharField(max_length=15),
        ),
    ]
